server:
  port: 8085
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_connection
    username: ${env.DB_USER:postgres}
    password: ${env.DB_PASSWORD:postgres}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types:
          print:
            banner: false
        metadata_builder_contributor: com.briolink.verificationservice.common.jpa.Functions
        jdbc:
          batch_size: 60
    generate-ddl: false
    show-sql: false
cloud:
  aws:
    stack:
      auto: false
event:
  listener:
    sqs-name: bl-network-${env.spring_profiles_active}-verification-service.fifo
app:
  app-endpoints:
    company: http://company-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    companyservice: http://companyservice-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    user: http://user-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    email: http://email-service.${env.spring_profiles_active}.svc.cluster.local/
    frontend: https://${env.spring_profiles_active}.briolink.com/
    auth: https://auth.${env.spring_profiles_active}.briolink.com/
permission-service:
  api:
    url: http://permission-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1
location-service:
  api:
    url: http://location-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1
sync-service:
  api:
    url: http://sync-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1