server:
  port: 8085
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_exp_verification
    username: ${env.DB_USER:postgres}
    password: ${env.DB_PASSWORD:postgres}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types:
          print:
            banner: false
        metadata_builder_contributor: com.briolink.expverificationservice.common.jpa.Functions
        jdbc:
          batch_size: 60
    generate-ddl: false
    show-sql: false
cloud:
  aws:
    stack:
      auto: false
event:
  listener:
    sqs-name: bl-network-${env.spring_profiles_active}-exp-verification-service.fifo
sync-service:
  api:
    url: http://sync-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1